---
  - name: add nodejs repo
    apt_repository: repo='ppa:chris-lea/node.js' state=present

  - apt: name={{item}} update_cache=yes state=present
    with_items: [python-software-properties, python, g++, make, nodejs]
