---
- hosts: all
  sudo: yes
  roles:
    - base-packages
    - rvm
    - oracle-jdk
    - maven
    - golang
    - phantomjs
    - nodejs

  tasks:
    - name: add mysql client config
      template: src=templates/my.cnf dest=/etc/my.cnf owner=root group=root mode=644

    - name: install aws tools
      pip: name=awscli state=present

    - name: download eb tool
      get_url: url=https://s3.amazonaws.com/elasticbeanstalk/cli/AWS-ElasticBeanstalk-CLI-2.6.3.zip dest=/opt/

    - name: unarchive eb tool
      unarchive: src=/opt/AWS-ElasticBeanstalk-CLI-2.6.3.zip dest=/opt/ copy=no creates=/opt/AWS-ElasticBeanstalk-CLI-2.6.3

    - name: symlink eb dir
      file: src=/opt/AWS-ElasticBeanstalk-CLI-2.6.3 dest=/opt/eb state=link

    - name: symlink eb tool
      file: src=/opt/eb/eb/linux/python2.7/eb dest=/usr/bin/eb state=link
