---
  - name: download maven
    get_url:
      url=http://ftp.unicamp.br/pub/apache/maven/maven-3/3.2.1/binaries/apache-maven-3.2.1-bin.tar.gz
      dest=/usr/local/src/

  - name: unarchive maven
    unarchive:
      src=/usr/local/src/apache-maven-3.2.1-bin.tar.gz
      dest=/usr/local/
      copy=no

  - file: src=/usr/local/apache-maven-3.2.1 dest=/usr/local/maven state=link

  - file: src=/usr/local/maven/bin/mvn dest=/usr/local/bin/mvn state=link
